### ISSUE TITLE
[MJARSIGNER-21] jars signed using Java 7 have "invalid SHA1 signature"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jarsigner-plugin#79]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** opened **[MJARSIGNER-21](https://issues.apache.org/jira/browse/MJARSIGNER-21?redirect=false)** and commented

Using the plugin with Java 6 works fine. When I use it with Java 7, my applet won't load because the SHA1 signatures are invalid.

---

**Affects:** 1.2

**Issue Links:**
- [MSHARED-314](https://issues.apache.org/jira/browse/MSHARED-314) Unsigning a jar is not correct
 (_**"depends upon"**_)
- [MJARSIGNER-27](https://issues.apache.org/jira/browse/MJARSIGNER-27) Use maven-jarsigner 1.3
 (_**"is depended upon by"**_)

2 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** commented

Signing with JDK 7 and verifying with JDK 5 and 6 works for me. Can you try unsigning the archives prior to signing (removeExistingSignatures parameter) ? What exactly is invalid about the signatures ?

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

The applet is giving the following error when it downloads one of these jars:

java.lang.SecurityException: invalid SHA1 signature file digest for org/apache/log4j/net/DefaultEvaluator.class
at sun.security.util.SignatureFileVerifier.verifySection(Unknown Source)
at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
at sun.security.util.SignatureFileVerifier.process(Unknown Source)
at java.util.jar.JarVerifier.processEntry(Unknown Source)
at java.util.jar.JarVerifier.update(Unknown Source)
at java.util.jar.JarFile.initializeVerifier(Unknown Source)

I'm not exactly sure what pieces are required to make this happen. We have some jar files that are signed with our "production" certificate. In the development environment they are then also signed at build time with a test certificate. The ones signed using Java 6 work fine in this manner. Those signed with Java 7 give the error specified above. Three files are different between two jars signed in this way:

CODESIGN.DSA, CODESIGN.SF and MANIFEST.MF.

The most obvious difference is that the jar signed with Java 7 has SHA-256-Digest entries in addition to the SHA1 entries.

I can provide these jar files to someone to look at but would prefer not to upload.

**Comment by jira-importer** [comment]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** commented

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6561126
http://hg.openjdk.java.net/jdk7/tl/jdk/rev/29b076bfeafd

I think you need to use '-digestalg SHA-1' with JDK 7 or '-digestalg SHA-256' with JDK 6 to make this work.

```xml
<configuration>
  <arguments>
    <argument>-digestalg</argument>
    <argument>${jarsigner.digestalg}</argument>
  </argument>
</configuration>
```

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

That takes care of the issue. Some documentation within the plugin about default keysizes might be helpful.

**Comment by jira-importer** [comment]
**[Tony Chemit](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tchemit)** commented

FMU, there is no need to specify the digest algo. Just cleaning the manifest while unsigning a jar befoire resign it should be sufficent. See MSHARED-314

**Comment by jira-importer** [comment]
**[Tony Chemit](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tchemit)** commented

Close since MSHARED-314 fix the problem.
